# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c3gciVO0ZJ58_hfY5GSrNmUPvPaQsE47
"""

import tensorflow as tf

directory_url = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/'
file_names = ['cowper.txt', 'derby.txt', 'butler.txt']

file_paths = [
    tf.keras.utils.get_file(file_name, directory_url + file_name)
    for file_name in file_names
]

dataset = tf.data.TextLineDataset(file_paths)

!pip3 install tensorflow_text

import tensorflow_text as tf_text

data_utf8 = map(lambda x:tf_text.normalize_utf8(x), dataset)

for i in data_utf8:
    print(i.numpy())

!pip3 show tensorflow

